### ISSUE TITLE
About cuda

### ISSUE THREAD

**Issue by Decalogue** [elvisyjlin/SpatialAttentionGAN#1]
Hi!
When I run train.py, it occured:
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    fakes, _ = G(reals, target_labels)
  File "/home/rain/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rain/nlp/etrump/txt2img/SAGAN_celeba/sagan.py", line 95, in forward
    y = self.AMN(x, a)
  File "/home/rain/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rain/nlp/etrump/txt2img/SAGAN_celeba/sagan.py", line 83, in forward
    x = torch.cat((x, a), dim=1)
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'

Can you help me with it?

Thank you so much!

**Comment by elvisyjlin** [comment]
Hi @Decalogue,
The error occurred in `labels.to(device).type_as(reals)`. The tensors were moved to the GPU but they were moved back to the CPU as the type changed afterward. It is supposed to be `labels.type_as(reals).to(device)`.
The scripts were updated in 3d7ac558ac00bd790fa03f205a173566ca89060c. You're able to get it updated by `git pull`.
Sorry for my late reply and thank you for reporting this! Please let me know if you have other questions.

**Comment by Decalogue** [comment]
Thank you so much!
