### ISSUE TITLE
CUDA problem in generate.py

### ISSUE THREAD

**Issue by DateBro** [elvisyjlin/SpatialAttentionGAN#4]
Thanks for your excellent work, but I got similar problem as #1.
```
Traceback (most recent call last):
  File "generate.py", line 80, in <module>
    samples, masks = G(reals, target_labels)
  File "/home/zhiyong/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhiyong/temp_test/SpatialAttentionGAN/sagan.py", line 98, in forward
    y = self.AMN(x, a)
  File "/home/zhiyong/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhiyong/temp_test/SpatialAttentionGAN/sagan.py", line 86, in forward
    x = torch.cat((x, a), dim=1)
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'
```
And I fixed it by modify the code in line76, generate.py.
```
reals, labels = reals.to(device), labels.type_as(reals).to(device)
```
Maybe you can update the generate.py to fix it.

**Comment by elvisyjlin** [comment]
Hi @DateBro, thank you for the modification. I've updated it in 80d453bd44fc9f27ed1b6553ee2c830fb02b4830.
